#!/bin/bash

set -e

if [ -z $1 ]
then
  echo "Usage: $0 localaccount_username"
  exit 1
fi

echo "Enabling local account $1@gmail.com."
echo "Remove ../platform/pam_google/pam_localaccount.h and "
echo "../platform/pam_offline/pam_localaccount.h to disable."

cat <<EOF > ../platform/pam_google/pam_localaccount.h
// local username for Chrome OS pam
// This file is auto-generated by enable_localaccount.sh

#ifndef CHROMEOS_PAM_LOCALACCOUNT_H_
#define CHROMEOS_PAM_LOCALACCOUNT_H_

namespace chromeos_pam {
const char kLocalAccount[] = "$1@gmail.com";
}

#endif // CHROMEOS_PAM_LOCALACCOUNT_H_
EOF

cat <<EOF > ../platform/pam_offline/pam_localaccount.h
// local username for Chrome OS pam
// This file is auto-generated by enable_localaccount.sh

#ifndef CHROMEOS_PAM_LOCALACCOUNT_H_
#define CHROMEOS_PAM_LOCALACCOUNT_H_

namespace pam_offline {
const char kLocalAccount[] = "$1@gmail.com";
}

#endif // CHROMEOS_PAM_LOCALACCOUNT_H_
EOF
