#!/bin/bash

# Copyright (c) 2010 The Chromium OS Authors. All rights reserved.
# Use of this source code is governed by a BSD-style license that can be
# found in the LICENSE file.

# Lists all package dependencies of a particular package.  Useful to find out
# all packages depended on by chromeos and chromeos-dev.

SCRIPT_ROOT=$(dirname $(readlink -f "$0"))
. "${SCRIPT_ROOT}/common.sh" || exit 1

# Script must be run inside the chroot.
assert_inside_chroot

# Flags.
DEFINE_string board "$DEFAULT_BOARD" \
  "The board for which the image was built." b

# Parse flags.
FLAGS "$@" || exit 1
eval set -- "${FLAGS_ARGV}"

[[ -z "${FLAGS_board}" ]] && die_notrace "A board must be specified."

if [[ -z "${FLAGS_ARGV}" ]]; then
  warn "Usage:  ./get_package_list.sh chromeos-base/chromeos > package.list"
  die_notrace "Please specify a package."
fi

emerge-$FLAGS_board --emptytree --usepkgonly -p -v --columns \
  $1 2> /dev/null | sed -n -E -e 's/^\[binary[^]]*\] ([^ ]*) .*$/\1/p'
