#!/bin/bash

# Copyright (c) 2010 The Chromium OS Authors. All rights reserved.
# Use of this source code is governed by a BSD-style license that can be
# found in the LICENSE file.

# Run gmergefs from the scripts directory.

COMMON_SH="$(dirname "$0")/common.sh"
. "$COMMON_SH"

# Script must be run inside the chroot.
assert_inside_chroot

cd ${GCLIENT_ROOT}/src/platform/dev && ./gmergefs $*
