#!/bin/bash

# Copyright (c) 2010 The Chromium OS Authors. All rights reserved.
# Use of this source code is governed by a BSD-style license that can be
# found in the LICENSE file.

# Start the Dev Server after making sure we are running under a chroot.

# --- BEGIN COMMON.SH BOILERPLATE ---
# Load common CrOS utilities.  Inside the chroot this file is installed in
# /usr/lib/crosutils.  Outside the chroot we find it relative to the script's
# location.
find_common_sh() {
  local common_paths=(/usr/lib/crosutils $(dirname "$(readlink -f "$0")"))
  local path

  SCRIPT_ROOT=
  for path in "${common_paths[@]}"; do
    if [ -r "${path}/common.sh" ]; then
      SCRIPT_ROOT=${path}
      break
    fi
  done
}

find_common_sh
. "${SCRIPT_ROOT}/common.sh" || (echo "Unable to load common.sh" && exit 1)
# --- END COMMON.SH BOILERPLATE ---

# Script must be run inside the chroot if not in 'always serve' mode.
if [[ "$1" != "--archive_dir" ]]; then
  restart_in_chroot_if_needed "$@"
fi

# Temporary workaround: to start devserver for update engine, pass in args
# --client_prefix ChromeOSUpdateEngine

# Set PKG_INSTALL_MASK if it's not set already.
if [ -z "${PKG_INSTALL_MASK+x}" ]; then
  export PKG_INSTALL_MASK="${DEFAULT_INSTALL_MASK}"
fi
echo PKG_INSTALL_MASK=$PKG_INSTALL_MASK

python "${GCLIENT_ROOT}/src/platform/dev/devserver.py" "$@"
