#!/bin/bash

# Copyright (c) 2011 The Chromium OS Authors. All rights reserved.
# Use of this source code is governed by a BSD-style license that can be
# found in the LICENSE file.
#
# Changes the channel of the image for test builds so that it will be
# identified as a test image to Omaha which will not give any updates.

echo "Modifying Release Track for Test (testimage-channel)."
FILE="${ROOT_FS_DIR}/etc/lsb-release"
sed -i 's/^\(CHROMEOS_RELEASE_TRACK=\).*/\1testimage-channel/' $FILE
