#!/bin/bash

# Copyright (c) 2009 The Chromium OS Authors. All rights reserved.
# Use of this source code is governed by a BSD-style license that can be
# found in the LICENSE file.

# reset password for root and shared user account.

LOCAL_ACCOUNT="chronos"
echo "Reset password for root."
passwd root < test_account.passwd 2> /dev/null
echo "Reset password for ${LOCAL_ACCOUNT}."
passwd ${LOCAL_ACCOUNT} < test_account.passwd 2> /dev/null

