#!/bin/bash

# Copyright (c) 2009 The Chromium OS Authors. All rights reserved.
# Use of this source code is governed by a BSD-style license that can be
# found in the LICENSE file.
#
# Copy public keys to root's homedir for ssh pubkey auth, which
# is necessary for test automation.

KEYS_DIR=ssh_keys
ROOT_AUTHKEYS=/root/.ssh/authorized_keys

mkdir -p /root/.ssh
cat ${KEYS_DIR}/* >> ${ROOT_AUTHKEYS}      
