#!/bin/bash

# Copyright (c) 2011 The Chromium OS Authors. All rights reserved.
# Use of this source code is governed by a BSD-style license that can be
# found in the LICENSE file.

echo "Modifying upstart scripts for test accessibility."
for script in "${ROOT_FS_DIR}/etc/init/*.conf"; do
    sed -i 's/#for_test //' ${script}
done

