#!/bin/bash

# Copyright (c) 2009 The Chromium OS Authors. All rights reserved.
# Use of this source code is governed by a BSD-style license that can be
# found in the LICENSE file.

# start sshd at os init time.

cp -pf sshd.conf /etc/init/sshd.conf

chmod 644 /etc/init/sshd.conf
chown 0:0 /etc/init/sshd.conf

