#!/bin/bash

# Copyright (c) 2009 The Chromium OS Authors. All rights reserved.
# Use of this source code is governed by a BSD-style license that can be
# found in the LICENSE file.

# enable autox login by disabling remembering of last username
echo "Enabling autologin using autox."
touch "${ROOT_FS_DIR}/root/.forget_usernames"

