#!/bin/bash

# Copyright (c) 2011 The Chromium OS Authors. All rights reserved.
# Use of this source code is governed by a BSD-style license that can be
# found in the LICENSE file.

echo "Configuring to enable root access to dbus-monitor"

cat > "${ROOT_FS_DIR}/etc/dbus-1/system-local.conf" <<EOF
<busconfig>
  <policy user="root">
    <allow send_destination="*" eavesdrop="true"/>
    <allow receive_sender="*" eavesdrop="true"/>
  </policy>
</busconfig>
EOF
