#!/bin/bash

# Copyright (c) 2012 The Chromium OS Authors. All rights reserved.
# Use of this source code is governed by a BSD-style license that can be
# found in the LICENSE file.

# session_manager_setup.sh checks for this USE flag.
# TODO(jimhebert) Once crosbug.com/13429 is fixed and test-builds can
# be produced with different USE flags, we can eliminate this
# mod_for_test script in favor of a real USE flag for
# chromeos-base/chromeos-login.
echo "Enabling use of SSLKEYLOGFILE in Chrome."
echo dangerous_sslkeylogfile >> \
  "${ROOT_FS_DIR}/etc/session_manager_use_flags.txt"
