#!/bin/bash

# Copyright (c) 2010 The Chromium OS Authors. All rights reserved.
# Use of this source code is governed by a BSD-style license that can be
# found in the LICENSE file.

echo "Disabling ui.conf, don't do Chrome startup on boot."
mv ${ROOT_FS_DIR}/etc/init/ui.conf ${ROOT_FS_DIR}/etc/init/ui.conf.disabled
