#!/bin/bash

# Copyright (c) 2010 The Chromium OS Authors. All rights reserved.
# Use of this source code is governed by a BSD-style license that can be
# found in the LICENSE file.

echo "Modifying Release Description for Factory."
FILE="${ROOT_FS_DIR}/etc/lsb-release"
sed -i 's/Test/Factory/' $FILE
