#!/bin/bash

# Copyright (c) 2010 The Chromium OS Authors. All rights reserved.
# Use of this source code is governed by a BSD-style license that can be
# found in the LICENSE file.

echo "Create global_config.ini in autotest directory."

GLOBAL_CONFIG="${ROOT_FS_DIR}/usr/local/autotest/global_config.ini"

if [ -f "${GLOBAL_CONFIG}" ]; then
  echo -e "File ${GLOBAL_CONFIG} already exists."
  exit 1
fi

AUTOTEST_DIR="${ROOT_FS_DIR}/usr/local/autotest/"

chmod +x factory_ui
cp "factory_ui" "${AUTOTEST_DIR}"
chmod +x factory_startx.sh
cp "factory_startx.sh" "${AUTOTEST_DIR}"

cat > "${GLOBAL_CONFIG}" <<EOF
[CLIENT]
drop_caches: False
drop_caches_between_iterations: False
EOF
