#!/bin/bash

# Copyright (c) 2010 The Chromium OS Authors. All rights reserved.
# Use of this source code is governed by a BSD-style license that can be
# found in the LICENSE file.

echo "Configure autotest setting."

SCRIPT_DIR="${GCLIENT_ROOT}/src/scripts/mod_for_factory_scripts/"
AUTOTEST_DIR="${ROOT_FS_DIR}/usr/local/autotest/"

cp "${SCRIPT_DIR}/factory_ui" "${AUTOTEST_DIR}"
chmod +x "${AUTOTEST_DIR}/factory_ui"
cp "${SCRIPT_DIR}/factory_startx.sh" "${AUTOTEST_DIR}"
chmod +x "${AUTOTEST_DIR}/factory_startx.sh"

GLOBAL_CONFIG="${ROOT_FS_DIR}/usr/local/autotest/global_config.ini"

if [ -f "${GLOBAL_CONFIG}" ]; then
  echo -e "File ${GLOBAL_CONFIG} already exists."
  exit 1
fi

cat > "${GLOBAL_CONFIG}" <<EOF
[CLIENT]
drop_caches: False
drop_caches_between_iterations: False
EOF
