#!/bin/bash

# Copyright (c) 2010 The Chromium OS Authors. All rights reserved.
# Use of this source code is governed by a BSD-style license that can be
# found in the LICENSE file.

TEST_DIR="${ROOT_FS_DIR}/usr/local/autotest/site_tests/hardware_Components"
COMPONENTS_FILE="${TEST_DIR}/qualified_components"

# If QUALDB not specified, use the one based on board name.
if [ -z ${QUALDB} ]; then
  QUALDB="${TEST_DIR}/qualified_components_${BOARD}"
fi

if [ ! -z ${QUALDB} ] && [ -f ${QUALDB} ]; then
  # Copy the qualified component file to the image
  echo "Copying ${QUALDB} to the image."
  cp -f ${QUALDB} ${COMPONENTS_FILE}
else
  echo "No qualified component file found at: ${QUALDB}"
fi
