#!/bin/bash

# Copyright (c) 2010 The Chromium OS Authors. All rights reserved.
# Use of this source code is governed by a BSD-style license that can be
# found in the LICENSE file.

TEST_DIR="${ROOT_FS_DIR}/usr/local/autotest/site_tests/factory_WriteGBB"

pushd ${TEST_DIR} 1> /dev/null

GBB_FILE="gbb_${BOARD}*"
FIRST_GBB_FILE=$(ls $GBB_FILE 2> /dev/null | head -1)
if [ -e "${FIRST_GBB_FILE}" -o "${BOARD}" = "x86-generic" ]; then
  # Remove GBB files belonging to other boards
  ls gbb* 2> /dev/null | grep -v gbb_${BOARD} | xargs rm -f
else
  echo "No GBB file found at: ${GBB_FILE}"
fi

popd 1> /dev/null
